api:
  security:
    token:
      secret: ${JWT_SECRET}
application:
  developer:
    name: Lucas de Oliveira Macedo
    email: lucasomac@outlook.com
server:
  error:
    include-stacktrace: never
spring:
  datasource:
    url: ${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true