api:
  security:
    token:
      secret: ${JWT_SECRET:12345678}
server:
  error:
    include-stacktrace: never
spring:
  application:
    name: Med Vol API
    developer:
      name: Lucas de Oliveira Macedo
      email: lucasomac@outlook.com
      url: https://www.linkedin.com/in/lucasomac/
  profiles:
    active: dev
springdoc:
  swagger-ui:
    path: /swagger.html